
language: android
sudo: required
jdk: oraclejdk8

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/


env:
 global:
 - ANDROID_API=26
 - EMULATOR_API=22
 - ANDROID_BUILD_TOOLS=26.0.1
 - ANDROID_ABI=armeabi-v7a
 - ANDROID_TAG=google_apis
 - ADB_INSTALL_TIMEOUT=2 # minutes
 - secure:"btrii3ex8XJwkn7dhzR/309hzDMCnaR+5IkqaeOnqEBI53eZJpLvkABheKmb2Y21LeqKswYrQtOhoxaOMpx3pu2dAHgTfwWO4u9g6cEZqS+xuNqd0P2pzV5AYYpAzGcU40bWDK3JPxNm6nP3MmIhzGHZOJgisIVALXWxdygHHuoGDA9cnRk6WqRs6FU6SfcJQXwn08UmvavYwiL+ykR2bGJbIviMf/6j7aEZcLUyj34792l0DyzCLWtVJAxNhSxdY5a3yqrjFg6IWoSV/cI+lJVSmh6fK7nAheG4xx36ZFxELz37MS2fy5vmdPdPbt+SYUJEkIATCoZQATnsK81tg7rpHTC0HWuEf7ND1xflJs3RgZ2Z2RKMVWuBeShg51kWgxZLoPil37sCIUAEGrDmTqqHndaT4wabak/VO72/88CXFSrzpHOy6WJFrkwdPXPY2LxRt+yfwE5EFVgsMyKMhywdYF5BHkJd7MCWEoJncEXMiWmKscBOUK4uJM2kRGZIDXeb5DLeJjN6IW6wEg1crvdFhjbr9vWwTMuYhyikJGTvxhvHn+yZ8LT2coNX3ASX+grGhw6wuZWldbWRYiXBq7iJiqo/MjYmdsz+QghrcIi6tpp4Na7LBnubMlo0k3emj1F1YXT7NKxXd7OP1iAjO22BYug6xtsDjFIR6AuaP5M="
 - secure:"htR/IJl0GD6IFVUcUYRKqH3hXAcvHlgEineE6a4TtFgLIpm3Ui15nsyDUvFyJ3dOdNkgXZ1Q+AAZ2pAhyBEk3D/mG5T+5v7RhWq7HYuY4Cd3aLbLHlptihTOdQk92SxN3JisJwX24DN8Pf2e5SdVgExgKMA3RH2i2nmUmye5NmfZS8USstfJlKvlkXKS+vYNZUn6dnI9FIKv4BAs+0BVWuXmcRJs0m9w/eXxKQjFEYcXYJFrdKKVqWYs/2l4swP6LHp0SJ469y5p8A8Lx/+P9ofDplRioa+uSMPEXDo071hBko1r7G47KAFSMIpv1WwA6cfRnHzYvUvBRP+b8sGfc4lO7FOynrUYRkCAQBYwKlJ0IUXg012tufKoa/u5YRS5sXB0a4gXp9c4gmjDCP0ZQZWDI6jXkK1DXBfeV/DHMMXE0dztbQACbpHidky6DndGXIKBxPla7LSeDVqE418qMs9s4tvGs4BCpJycZ7CV6JLqxBBD6ZJGsIHI56F9flWbSPwJzrNOJep63x2L36ht4+Y1XyYi5Cd4W5QhZ+/yp6tDZbvwVLyYvmDXXPDFns51Y8unDG5uxWrm5AlN1JQ9P4I7lH1Ay+zaXUm54/cJcEaiH+YfJ3pTsP8lkT8mqUPsd6+Yh2mHr71zEjz/2zCyPOvJSYd9YPgDFRCpCMr2k/I="

android:
 components:
 - tools
 - platform-tools
 - tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-$ANDROID_API
 - addon-google_apis-google-$EMULATOR_API
 - extra-google-google_play_services
 - extra-android-support
 - addon-google_apis-google-19 # google play services
 - sys-img-armeabi-v7a-google_apis-25

 licenses:
   - android-sdk-preview-license-.+
   - android-sdk-license-.+
   - google-gdk-license-.+

before_install:
  - openssl aes-256-cbc -K $encrypted_f439949bde01_key -iv $encrypted_f439949bde01_iv -in kotlin-mvp.jks.enc -out kotlin-mvp.jks -d
  - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-25 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace

before_deploy:
  - cp $TRAVIS_BUILD_DIR/.keystore $HOME
  - cd app/build/outputs/apk/
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/kotlin-mvp.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk Kotlin-MVP

  # Verification
  - jarsigner -verify app-release-unsigned.apk
  - "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk kotlinmvp.apk"

deploy:
  provider: releases
  file: kotlinmvp.apk
  skip_cleanup: true

  on:
    repo: GopherLabsLtd/android-clean-architecture
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: "gogCNfZwaP8Zf8IkxDnoEMlq5txkgWv19/87JKwbZHr1VL2kyEWRKDgcvhXgZzXRRa7Vr+POc7iPkB9Q03sjAQTb/JgOv1ZZ2bxCnJHCEs7r3NpgbyQg7wCs82BbaZSA3A7uUuGWkgnKIQzoJvOtJNUo+7nBELZ9r6Mq1OwqsJD7raj5hwZA64MMerKd/mG7zSXXOSkYAn6tYphfK3EYv311OJeoq7b9qavF3EQe+lAlHnDTE0jmmpqYtF7H+uYfT1w2DmMW903yCbZeaBsLJPIs0pAUZQGNe/uhZ5Jt/Y5Ee/xBnunT00Sg7BqBqUSo3ZcmMJc60lMI3cNAMGXz1F/yp21ZtTQtSycr4cEbbrzUCc3oDgAS7dIVlIjjylzw80AmXIXSMawVrTUlGKOKsg84l7Z910Yhu5qrDO7J3AP0mBB9DSTKT5BfU/n8dRlfUxDFVBzkxIBQW/xaQI5lGtSSA5gkF7l91JXduKT4PHdVX98TbYP9tTKpv28lYJjYgTSvp6SQpcX43bvhjBZJe7vRiBk/vk43UbaAdkvnpnmWsoYBPd3LLdezM7PypSzmeYQvVV9z5ooY930/vwMnuCdHNw4bcPGZhOg35LHDVudIIoJON2UnePxhR6MVNBqW2lDn/hci7vkNnikvysZK7NIT3I5EurIfLnXp6JZtN1M="
